### ISSUE TITLE
After the image generation fishish it desapear of the

### ISSUE THREAD

**Issue by merecesarchviz** [GeorgLegato/stable-diffusion-webui-vectorstudio#10]
hi, 

I got the addon installed and works without a error! but after i generate a image, it simple desapear after finish it! but during the render process thhe image shows up, only after finish the render it desapear! any idea what is happen?
![desapear](https://user-images.githubusercontent.com/79140456/233778505-a079e112-ed4a-46dd-9f8f-9ba3b2fb1fee.jpg)

**Comment by GeorgLegato** [comment]
you see it during rendering from SD, then the post-process seems to fail and does not give results back (png, svg).
check your console output, bot CMD where you started SD and open dev-tools and check the browser console log

**Comment by merecesarchviz** [comment]
in cmd, no error pop up! that is why is more extrange! it shows all the progress in rendering but until finish the image desapear!

**Comment by GeorgLegato** [comment]
please provide more screenshot. is it Automatic1111? (seems), collabs does not work anyways.
what are the settings in vectorstudio´s script panel (lower left corner)
do you have Setting enable: save output images?

**Comment by merecesarchviz** [comment]
Here is the settings pretty default!
![22](https://user-images.githubusercontent.com/79140456/233794186-f760cf39-b83e-4522-931e-4056623cac6e.jpg)

**Comment by GeorgLegato** [comment]
ok, look good. make a screenshot of browser console (F12 or Devtool activate) and from your command line).
Without error messages I cannot help.
Have you install POTRACE (.exe) to the bin folder?

**Comment by merecesarchviz** [comment]
Yes Potrace installed in bin folder, here is the screenshot of cmd after the render done, no errors!
![33](https://user-images.githubusercontent.com/79140456/233928478-24a33893-934c-46bb-8f30-061c26ea3864.jpg)

**Comment by rafaeldelrey** [comment]
This is happening with me too. It seems it is trying to find the portrace.exe file even though I m running on Linux

**Comment by merecesarchviz** [comment]
in my case the Potrace.exe is in the bin folder!

**Comment by 3D-CNC-Reutlingen** [comment]
> hi,
> 
> I got the addon installed and works without a error! but after i generate a image, it simple desapear after finish it! but during the render process thhe image shows up, only after finish the render it desapear! any idea what is happen? ![desapear](https://user-images.githubusercontent.com/79140456/233778505-a079e112-ed4a-46dd-9f8f-9ba3b2fb1fee.jpg)

i had this problem a few weeks ago too, but in general with auto1111, temporarly i fixed it by adding this to the style.css on top of the code:
#txt2img_gallery img, #img2img_gallery img {
    object-fit: scale-down;
    width: 300px;
    height: 300px;
}
maybe it will help you too.
i did a complete reinstall later, actually at first just wanted to update torch and some stuff but somehow broke it complete haha.

**Comment by mashb1t** [comment]
@merecesarchviz please make sure "Always save all generated images" is enabled and "File format for images" is png (will work with jpg/jpeg too though, but results will not be very good)

@GeorgLegato do you think adding a hint to this in the readme would make it easier for users to set this up in the future?

**Comment by playgrdstar** [comment]
Hi, I had this issue too. Solved it by downloading from https://potrace.sourceforge.net/#downloading. Extracted the potrace.exe from the file there and placed it in bin (replacing the one that was downloaded by the script).

**Comment by GeorgLegato** [comment]
latest release has autodownload feature now

**Comment by playgrdstar** [comment]
Thanks for the great work on this. Just to clarify, the auto download works. But I had the same issue when using the potrace.exe that was downloaded by the script. But when I replace with the one from the potrace website directly it works.
