### ISSUE TITLE
Appears to run fine but I get no image output. I've tried different models and settings to no avail.

### ISSUE THREAD

**Issue by Coda514** [GeorgLegato/stable-diffusion-webui-vectorstudio#13]
Here is my command window.

Already up to date.
venv "C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...

Installing requirements 1 for Infinite-Zoom

Launching Web UI with arguments: --vae-path models\Stable-diffusion\vae-ft-mse-840000-ema-pruned.pt --api --xformers --disable-safe-unpickle --api --cors-allow-origins=https://www.painthua.com
ControlNet v1.1.107
ControlNet v1.1.107
Loading weights [fe94665ac0] from C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\models\Stable-diffusion\vinteprotogenmixV10_.safetensors
Creating model from config: C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights from commandline argument: models\Stable-diffusion\vae-ft-mse-840000-ema-pruned.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(12): atompunkstylesd15, bad-artist-anime, bad-artist, bad-hands-5, bad_prompt_version2, CharTurner, EasyNegative, ghst-3000, logo-with-face-on-shield, ng_deepnegative_v1_75t, poly-hd, Style-Necromancy
Textual inversion embeddings skipped(14): anthro, cartoonish_doll, CGI_Animation, Em_diesel1, InkPunk768, laxpeint, midjourney-1250, mj-csp, nartfixer2_1, nfixer2_1, nrealfixer2_1, remix, SCG768-Euphoria, vray-render
Model loaded in 3.2s (load weights from disk: 0.2s, create model: 0.3s, apply weights to model: 0.5s, apply half(): 0.6s, load VAE: 0.2s, move model to device: 0.6s, load textual inversion embeddings: 0.9s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.1s (import torch: 1.5s, import gradio: 1.0s, import ldm: 0.4s, other imports: 0.9s, load scripts: 2.0s, load SD checkpoint: 3.5s, create ui: 2.6s, gradio launch: 0.1s).
Loading weights [ee10b26e6c] from C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\models\Stable-diffusion\coloringBook_coloringBook.ckpt
Creating model from config: C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\models\Stable-diffusion\coloringBook_coloringBook.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading VAE weights from commandline argument: models\Stable-diffusion\vae-ft-mse-840000-ema-pruned.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(14): anthro, cartoonish_doll, CGI_Animation, Em_diesel1, InkPunk768, laxpeint, midjourney-1250, mj-csp, nartfixer2_1, nfixer2_1, nrealfixer2_1, remix, SCG768-Euphoria, vray-render
Textual inversion embeddings skipped(12): atompunkstylesd15, bad-artist-anime, bad-artist, bad-hands-5, bad_prompt_version2, CharTurner, EasyNegative, ghst-3000, logo-with-face-on-shield, ng_deepnegative_v1_75t, poly-hd, Style-Necromancy
Model loaded in 2.6s (create model: 0.2s, apply weights to model: 0.6s, apply half(): 0.7s, load VAE: 0.2s, move model to device: 0.9s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.46it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.65it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.25it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.83it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.99it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.91it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00, 10.36it/s]

**Comment by Jonjo-Jefferson** [comment]
I am also having the same issue. Tried on two computers, the image generates, flashes up for a split second then vanishes

**Comment by GeorgLegato** [comment]
in the log is no error at all.
thats strange:
ok, a checklist:

* Windows. ok
* commit of sd-webui 22bcc, latest. ok

*check on your site:
in the extions/sd-webui-vectorsudio/ you need the potrace.
But if it is not present we get error on console log.

* lower left dropdown "Script":
Is "Vector Studio selected?"
IF yes, do you see "Vector Studio" toolbar under the gallery?

provide some screenshots please, i need more context around
* open dev-tools and then start rendering, check if you get javascript errors (which are not shown on cmd log)
*

**Comment by GeorgLegato** [comment]
I ve ested current version on my machine. it works. I send you screenshot, please check if you see any of these points.
![image](https://user-images.githubusercontent.com/7210708/234724063-b83c5f81-bd19-4410-92c7-9ad0924d2568.png)

**Comment by Coda514** [comment]
I tried again to reinstall the extension and had the same results as before, no image output. This time I did get errors in my command window, shown below. Sorry I am not more knowledgeable and cant figure this out on my own. Any help is greatly appreciated.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.40it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.48it/s]
Error completing request███████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  6.99it/s]
Arguments: ('{"prompt": "an insane clown face,(((lineart))),((low detail)),(simple),high contrast,sharp,2 bit,(((clean ink funny comic cartoon illustration)))", "all_prompts": ["an insane clown face,(((lineart))),((low detail)),(simple),high contrast,sharp,2 bit,(((clean ink funny comic cartoon illustration)))"], "negative_prompt": "", "all_negative_prompts": [""], "seed": -1, "all_seeds": [3941627415], "subseed": -1, "all_subseeds": [822227692], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "Euler a", "cfg_scale": 7, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "ee10b26e6c", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["an insane clown face,(((lineart))),((low detail)),(simple),high contrast,sharp,2 bit,(((clean ink funny comic cartoon illustration)))\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3941627415, Size: 512x512, Model hash: ee10b26e6c"], "styles": [], "job_timestamp": "20230427102826", "clip_skip": 1, "is_using_inpainting_conditioning": false}', [], False, -1) {}
Traceback (most recent call last):
  File "C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\modules\ui_common.py", line 82, in save_files
    writer.writerow([data["prompt"], data["seed"], data["width"], data["height"], data["sampler_name"], data["cfg_scale"], data["steps"], filenames[0], data["negative_prompt"]])
IndexError: list index out of range

Error completing request
Arguments: ('{"prompt": "an insane clown face,(((lineart))),((low detail)),(simple),high contrast,sharp,2 bit,(((clean ink funny comic cartoon illustration)))", "all_prompts": ["an insane clown face,(((lineart))),((low detail)),(simple),high contrast,sharp,2 bit,(((clean ink funny comic cartoon illustration)))"], "negative_prompt": "", "all_negative_prompts": [""], "seed": -1, "all_seeds": [3941627415], "subseed": -1, "all_subseeds": [822227692], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "Euler a", "cfg_scale": 7, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "ee10b26e6c", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["an insane clown face,(((lineart))),((low detail)),(simple),high contrast,sharp,2 bit,(((clean ink funny comic cartoon illustration)))\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3941627415, Size: 512x512, Model hash: ee10b26e6c"], "styles": [], "job_timestamp": "20230427102826", "clip_skip": 1, "is_using_inpainting_conditioning": false}', [], False, -1) {}
Traceback (most recent call last):
  File "C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\modules\ui_common.py", line 82, in save_files
    writer.writerow([data["prompt"], data["seed"], data["width"], data["height"], data["sampler_name"], data["cfg_scale"], data["steps"], filenames[0], data["negative_prompt"]])
IndexError: list index out of range

**Comment by Jonjo-Jefferson** [comment]
I dont get any errors in the console on generation however i get an error on startup (confirmed its this extension as i dont get the svg error when disabled) and then if i click the cycle bg buttons the other error comes up. This is the same on both my computers.
Potrace.exe is in the bin folder also
These are the only errors I am getting, unsure if its causing the issue?
)


![error](https://user-images.githubusercontent.com/92127143/234915372-596f81ad-bd02-4866-b11b-117293c6834c.png)
![Untitled2](https://user-images.githubusercontent.com/92127143/234918165-d4bea07b-9f3b-41d7-a4a0-0afbbca58dd4.png)
![Untitled2](https://user-images.githubusercontent.com/92127143/234915393-e054c517-c454-4e11-a741-f6622d1559aa.png)

**Comment by GeorgLegato** [comment]
No, everything "svgcanvas" related is just the svg-editor tries to open an nonexisting document.
the yellow warnings are just missing translations. so there is nothing related to be seen.
if there errore they are at the end of the console output, svgcanvas errors are on startup. 
just COPY the whole console.log as text and paste it here or upload as file.

**Comment by GeorgLegato** [comment]
```
Traceback (most recent call last):
File "C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\modules\call_queue.py", line 56, in f
res = list(func(*args, **kwargs))
File "C:\Users\Matt\Stable_new\stable-diffusion-webui\stable-diffusion-webui\modules\ui_common.py", line 82, in save_files
writer.writerow([data["prompt"], data["seed"], data["width"], data["height"], data["sampler_name"], data["cfg_scale"], data["steps"], filenames[0], data["negative_prompt"]])
IndexError: list index out of range
```
here is something interesting, it seems before the vectorizer is called something crashes before. I check the code at this line 82 whats there...

**Comment by GeorgLegato** [comment]
Ensure this checkbox is ON, the extension is postprocessing an existing PNG-FILE from SD. I can reproduce the behavior you describe, when i turn off this button. If there is no file, no postprocessing possible. I could do it, but then I need to save the in-memory-image "somewhere" and mess up your harddrive. So, please option on.

** dont forget to click on ApplySettings**

![image](https://user-images.githubusercontent.com/7210708/234998642-ea65f7ac-e81a-44cb-a7e2-e16035116c5d.png)

**Comment by Coda514** [comment]
> Ensure this checkbox is ON, the extension is postprocessing an existing PNG-FILE from SD. I can reproduce the behavior you describe, when i turn off this button. If there is no file, no postprocessing possible. I could do it, but then I need to save the in-memory-image "somewhere" and mess up your harddrive. So, please option on.
> 
> ** dont forget to click on ApplySettings**
> 
> ![image](https://user-images.githubusercontent.com/7210708/234998642-ea65f7ac-e81a-44cb-a7e2-e16035116c5d.png)

Thank you so much. Turning on "Always save all generated images" did the trick.

**Comment by GeorgLegato** [comment]
Have fun!
