### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by Woipi** [GeorgLegato/stable-diffusion-webui-vectorstudio#14]
Hello,

since the newest update, the plugin is complaining about a missing "requirements.txt" file with the following error message:

Error running install.py for extension C:\StableDiffusion\extensions\stable-diffusion-webui-vectorstudio.
Command: "C:\StableDiffusion\venv\Scripts\python.exe" "C:\StableDiffusion\extensions\stable-diffusion-webui-vectorstudio\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "C:\StableDiffusion\extensions\stable-diffusion-webui-vectorstudio\install.py", line 60, in <module>
    reqs = json.load(open(req_file))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\StableDiffusion\\extensions\\stable-diffusion-webui-vectorstudio\\requirements.txt'

**Comment by theallyprompts** [comment]
I also get this error. New user, fresh install.

**Comment by Kizzyme** [comment]
same here, 
Error running install.py for extension C:\\..stable-diffusion-webui\extensions\stable-diffusion-webui-vectorstudio.
Command: "C:\\....stable-diffusion-webui\venv\Scripts\python.exe" "C:\\..stable-diffusion-webui\extensions\stable-diffusion-webui-vectorstudio\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "c:\\..stable-diffusion-webui\extensions\stable-diffusion-webui-vectorstudio\install.py", line 60, in <module>
    reqs = json.load(open(req_file))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\..stable-diffusion-webui\\extensions\\stable-diffusion-webui-vectorstudio\\requirements.txt'

**Comment by GeorgLegato** [comment]
right, this file has to be there. I added an empty now again.
