### ISSUE TITLE
Error - Exexution of Potrace failed

### ISSUE THREAD

**Issue by DerBaron10** [GeorgLegato/stable-diffusion-webui-vectorstudio#16]
The images seems to generate to 100%, but then i get this error and the image is deleted. 

Exception: VectorStudio: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)

I am using mac m1 pro. I have installed Potrace automatically after the first image generation with vectorstudio and also installed it using homebrew.

**Comment by DerBaron10** [comment]
okay the images are saved in the finder under outputs. so i guess there is an error but it doesnt matter. maybe someone who is more of an expert can tell me if i should do anything about this error message 😅

**Comment by GuruVirus** [comment]
I'm getting the same thing on Win11
`vectorstudio.py", line 218, in run
    raise Exception("VectorStudio: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)")`
And yes the normal gen'd PNG files are being saved however instead of expected SVG output I am getting **.pnm** files (they open in GIMP). It appears that this is an intermediary before the SVG conversion?

**Comment by GeorgLegato** [comment]
I havent tested it well on macos, i can do it tomorrow to check your probs

**Comment by bourneash** [comment]
I am running in to the same issue:
Exception: VectorStudio: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)

Using a Linux system (not WSL), Ubuntu 22.04.
Potrace is installed: 
`which potrace
/usr/bin/potrace`

**Comment by bourneash** [comment]
Little more info on this (Ubuntu 22.04)
The potrace file is not being set with the +x flag, 
`-rw-rw-r-- 1 user user  22K Sep 17  2019 potrace`

Trying to execute potrace manually yields this:
`extensions/stable-diffusion-webui-vectorstudio/bin/potrace
zsh: permission denied: extensions/stable-diffusion-webui-vectorstudio/bin/potrace`

If I manually `chmod +x` on the file  that and trying to run it, I get:
`extensions/stable-diffusion-webui-vectorstudio/bin/potrace -h
extensions/stable-diffusion-webui-vectorstudio/bin/potrace: 1: Syntax error: "(" unexpected`


If I copy my system potrace in to the extension folder like such:
`cp /usr/bin/potrace extensions/stable-diffusion-webui-vectorstudio/bin/potrace`

Then I am up and running and the SVG's are generated.

**Comment by Torbat** [comment]
I had the same error.

I downloaded the potrace.exe file for my OS (Win_10 x 64) from here:
https://potrace.sourceforge.net/#downloading

And I replaced the file here:
\stable-diffusion-webui\extensions\stable-diffusion-webui-vectorstudio\bin\potrace.exe 

Now everything works.
