### ISSUE TITLE
Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)

### ISSUE THREAD

**Issue by PatricioFernandezF** [GeorgLegato/stable-diffusion-webui-vectorstudio#2]
Good morning,
When i try to activate vectorstudio to export to svg in txt2image in automatic i get this error:
          TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)

¿What i can do?
Thanks you in advance

**Comment by GeorgLegato** [comment]
check you console output where you start SD from.
check if you have downloaded Potrace and it is in extensionfolder/bin
check if you save images at all; it depends that your images ae saved to like "outputs"..

**Comment by PatricioFernandezF** [comment]
Hello again, thanks. Im running it on colab (fastben Notebook). I Will check that when arrive home.

**Comment by GeorgLegato** [comment]
Collab is not supported. it runs on *some* foreign environment, which unknown constraint etc.
This extension is only tested on SD-Webui on local machine.
I have no time to investigate different collabs
