### ISSUE TITLE
Making This Work In Debian Distro

### ISSUE THREAD

**Issue by bitshifter52** [GeorgLegato/stable-diffusion-webui-vectorstudio#5]
There are a couple of things needed to make this work in a Debian/Ubuntu distro:

Install potrace:

sudo apt install potrace

Create symlink:

create a folder "bin" in stable-diffusion-webui-vectorstudio
from the command line (shell) in the stable-diffusion-webui-vectorstudio/bin run

ln -s /usr/bin/potrace potrace.exe

In vectorstudio.py make the following change:

_#        PO_TO_CALL = scripts.basedir() + "\\extensions\\stable-diffusion-webui-vectorstudio\\bin\\potrace.exe"
        PO_TO_CALL = scripts.basedir() + "/extensions/stable-diffusion-webui-vectorstudio/bin/potrace.exe"_

Hope this helps someone.

**Comment by GeorgLegato** [comment]
good point
I will add the "bin" folder to git. since empty folders not possible in git, I`ll add a readme.txt.
furhtermore I can fix the slashes path-part for good in code,

**Comment by GeorgLegato** [comment]
changes done, soon merged into main for public update
