### ISSUE TITLE
SVG 

### ISSUE THREAD

**Issue by fahabib** [GeorgLegato/stable-diffusion-webui-vectorstudio#7]
I got this error
Exception: TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)

**Comment by GeorgLegato** [comment]
have you downloaded POTRACE and put it in sd-folder/extensions/"sd-vectorstudio"/bin?
check setting->save each file (to ouput per default), it is postprocessing, without a file nothing can be done

**Comment by fahabib** [comment]
Shall i use this on colab and kaggle it will give result

**Comment by GeorgLegato** [comment]
don't know, collab is neither tested nor supported. collabs are special variants.
it is dedicated to sd webui automatic 1111  on local machine, run by webui-user.bat to be served on localhost:7860

**Comment by fahabib** [comment]
> don't know, collab is neither tested nor supported. collabs are special variants. it is dedicated to sd webui automatic 1111 on local machine, run by webui-user.bat to be served on localhost:7860

Thank you
